#!/bin/bash
echo "GitHubへのプッシュ手順:"
echo ""
echo "1. 以下のコマンドをコピーして実行してください："
echo ""
echo "git push https://yasuyuki-shiozawa:<YOUR_PAT>@github.com/yasuyuki-shiozawa/transcription-system.git main"
echo ""
echo "※ <YOUR_PAT> を実際のPersonal Access Tokenに置き換えてください"
echo ""
echo "2. または、Windows側のコマンドプロンプトで："
echo "cd C:\\Users\\shioz\\Downloads\\transcription-system"
echo "git push -u origin main"
echo ""
echo "プッシュ後、このファイルは削除してください。"