#!/bin/bash

echo "議会議事録作成システム - 開発環境起動スクリプト"
echo ""
echo "=== 起動手順 ==="
echo ""
echo "1. PostgreSQLのセットアップ（Windows側で実行）:"
echo "   - PostgreSQLをインストール"
echo "   - データベースとユーザーを作成:"
echo "     CREATE USER transcription WITH PASSWORD 'transcription123';"
echo "     CREATE DATABASE transcription_system OWNER transcription;"
echo ""
echo "2. バックエンドの起動:"
echo "   cd backend"
echo "   npm run prisma:generate"
echo "   npm run prisma:migrate"
echo "   npm run dev"
echo ""
echo "3. フロントエンドの起動（別ターミナル）:"
echo "   cd frontend"
echo "   npm run dev"
echo ""
echo "4. アクセスURL:"
echo "   - フロントエンド: http://localhost:3000"
echo "   - バックエンドAPI: http://localhost:3001"
echo "   - ヘルスチェック: http://localhost:3001/health"
echo ""
echo "=== Docker環境を使用する場合 ==="
echo "Windows側のコマンドプロンプトで:"
echo "   cd C:\\Users\\shioz\\Downloads\\transcription-system"
echo "   docker-compose up -d"